name: Build
run-name: build ${{ github.ref_name }}
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04 [Beta]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
         name: dist-without-markdown
         path: |
           dist
           !dist/**/*.md